spring:
      application:
        name: department-service
      jpa:
      show-sql: true
      h2:
      console:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

      
